#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("wheres.my.check.nysif.Droid.Resource", IsApplication=true)]

namespace wheres.my.check.nysif.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int nysif_black = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int nysif_blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int nysif_grey = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int nysif_red = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int nysif_teal = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_stacked_tab_max_width = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int button_long = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int header_text = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int long_button = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_to_wheres_my_check_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar_form_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int divider = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fb_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int instagram_logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int nysif_logo_splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int nysif_logo_top_bar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int oval_2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int path_2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int retrieve_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int settings_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int settings_icon_active = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int submit_button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int twitter_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int youtube_icon = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090042
			public const int button = 2131296322;
			
			// aapt resource value: 0x7f090024
			public const int button2 = 2131296292;
			
			// aapt resource value: 0x7f090032
			public const int button3 = 2131296306;
			
			// aapt resource value: 0x7f09001b
			public const int buttonBack = 2131296283;
			
			// aapt resource value: 0x7f090038
			public const int buttonFGoToLogin = 2131296312;
			
			// aapt resource value: 0x7f090033
			public const int buttonForgot = 2131296307;
			
			// aapt resource value: 0x7f090076
			public const int buttonSubmit = 2131296374;
			
			// aapt resource value: 0x7f090061
			public const int calendar_form_button = 2131296353;
			
			// aapt resource value: 0x7f090072
			public const int checkBox = 2131296370;
			
			// aapt resource value: 0x7f090040
			public const int checkboxKeep = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int checkboxShow = 2131296321;
			
			// aapt resource value: 0x7f090075
			public const int chekcBox = 2131296373;
			
			// aapt resource value: 0x7f090047
			public const int divider1 = 2131296327;
			
			// aapt resource value: 0x7f090008
			public const int divider1A = 2131296264;
			
			// aapt resource value: 0x7f090052
			public const int divider2 = 2131296338;
			
			// aapt resource value: 0x7f09000c
			public const int divider2A = 2131296268;
			
			// aapt resource value: 0x7f090069
			public const int divider3 = 2131296361;
			
			// aapt resource value: 0x7f09000f
			public const int divider3A = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int divider4A = 2131296274;
			
			// aapt resource value: 0x7f09004a
			public const int editClaimNumber = 2131296330;
			
			// aapt resource value: 0x7f090060
			public const int editDateOfBirth = 2131296352;
			
			// aapt resource value: 0x7f090064
			public const int editEmailAddress = 2131296356;
			
			// aapt resource value: 0x7f090055
			public const int editFirstName = 2131296341;
			
			// aapt resource value: 0x7f09004b
			public const int editLastFour = 2131296331;
			
			// aapt resource value: 0x7f09005a
			public const int editLastName = 2131296346;
			
			// aapt resource value: 0x7f090057
			public const int editMiddleInitial = 2131296343;
			
			// aapt resource value: 0x7f09006f
			public const int editPassword = 2131296367;
			
			// aapt resource value: 0x7f09005d
			public const int editTelephone = 2131296349;
			
			// aapt resource value: 0x7f090031
			public const int editText = 2131296305;
			
			// aapt resource value: 0x7f09003d
			public const int editText2 = 2131296317;
			
			// aapt resource value: 0x7f09003f
			public const int editText3 = 2131296319;
			
			// aapt resource value: 0x7f090020
			public const int editText5 = 2131296288;
			
			// aapt resource value: 0x7f09001f
			public const int editText6 = 2131296287;
			
			// aapt resource value: 0x7f09006c
			public const int editUsername = 2131296364;
			
			// aapt resource value: 0x7f090067
			public const int editVerifyEmail = 2131296359;
			
			// aapt resource value: 0x7f090071
			public const int editVerifyPassword = 2131296369;
			
			// aapt resource value: 0x7f090050
			public const int editZipCode = 2131296336;
			
			// aapt resource value: 0x7f09002b
			public const int gridview = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int gridview1 = 2131296300;
			
			// aapt resource value: 0x7f090079
			public const int imageView = 2131296377;
			
			// aapt resource value: 0x7f09001e
			public const int imageView3 = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int imageView4 = 2131296285;
			
			// aapt resource value: 0x7f09002d
			public const int imageView7 = 2131296301;
			
			// aapt resource value: 0x7f090018
			public const int imgFacebookLogo = 2131296280;
			
			// aapt resource value: 0x7f090015
			public const int imgInstagramLogo = 2131296277;
			
			// aapt resource value: 0x7f090002
			public const int imgLogo = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int imgPath = 2131296257;
			
			// aapt resource value: 0x7f090014
			public const int imgPathCenter = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int imgPathLeft = 2131296278;
			
			// aapt resource value: 0x7f090019
			public const int imgPathRight = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int imgTwitterLogo = 2131296279;
			
			// aapt resource value: 0x7f09001a
			public const int imgYoutubeLogo = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int relativeLayout = 2131296284;
			
			// aapt resource value: 0x7f090000
			public const int relativeLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090039
			public const int relativeLayout2 = 2131296313;
			
			// aapt resource value: 0x7f09002e
			public const int relativeLayout3 = 2131296302;
			
			// aapt resource value: 0x7f090048
			public const int starClaimNumber = 2131296328;
			
			// aapt resource value: 0x7f09005e
			public const int starDateOfBirth = 2131296350;
			
			// aapt resource value: 0x7f090062
			public const int starEmailAddress = 2131296354;
			
			// aapt resource value: 0x7f090053
			public const int starFirstName = 2131296339;
			
			// aapt resource value: 0x7f09004c
			public const int starLastFour = 2131296332;
			
			// aapt resource value: 0x7f090058
			public const int starLastName = 2131296344;
			
			// aapt resource value: 0x7f09006d
			public const int starPassword = 2131296365;
			
			// aapt resource value: 0x7f09005b
			public const int starTelephone = 2131296347;
			
			// aapt resource value: 0x7f09006a
			public const int starUsername = 2131296362;
			
			// aapt resource value: 0x7f090065
			public const int starVerifyEmail = 2131296357;
			
			// aapt resource value: 0x7f09004e
			public const int starZipCode = 2131296334;
			
			// aapt resource value: 0x7f09000e
			public const int text1 = 2131296270;
			
			// aapt resource value: 0x7f090011
			public const int text2 = 2131296273;
			
			// aapt resource value: 0x7f090004
			public const int textAbout = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int textAboutAppVersion = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int textAboutExplanation = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int textAboutRateApp = 2131296263;
			
			// aapt resource value: 0x7f090073
			public const int textCheckBox = 2131296371;
			
			// aapt resource value: 0x7f090074
			public const int textCheckBox1 = 2131296372;
			
			// aapt resource value: 0x7f090068
			public const int textChooseYourUserNameAndPassword = 2131296360;
			
			// aapt resource value: 0x7f090049
			public const int textClaimNumber = 2131296329;
			
			// aapt resource value: 0x7f090029
			public const int textClaimNumberC = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int textClaimNumberC1 = 2131296298;
			
			// aapt resource value: 0x7f090027
			public const int textClaimantName = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int textClaimantName1 = 2131296296;
			
			// aapt resource value: 0x7f090051
			public const int textContactInformation = 2131296337;
			
			// aapt resource value: 0x7f090009
			public const int textContactUs = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int textContactUsExplanation = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int textContactUsPhoneNumber = 2131296267;
			
			// aapt resource value: 0x7f09005f
			public const int textDateOfBirth = 2131296351;
			
			// aapt resource value: 0x7f090063
			public const int textEmailAddress = 2131296355;
			
			// aapt resource value: 0x7f090054
			public const int textFirstName = 2131296340;
			
			// aapt resource value: 0x7f090013
			public const int textFollow = 2131296275;
			
			// aapt resource value: 0x7f09004d
			public const int textLastFour = 2131296333;
			
			// aapt resource value: 0x7f090059
			public const int textLastName = 2131296345;
			
			// aapt resource value: 0x7f090056
			public const int textMiddleInitial = 2131296342;
			
			// aapt resource value: 0x7f09006e
			public const int textPassword = 2131296366;
			
			// aapt resource value: 0x7f09000d
			public const int textPrivacyStatement = 2131296269;
			
			// aapt resource value: 0x7f09005c
			public const int textTelephone = 2131296348;
			
			// aapt resource value: 0x7f090010
			public const int textTermsConditions = 2131296272;
			
			// aapt resource value: 0x7f09006b
			public const int textUsername = 2131296363;
			
			// aapt resource value: 0x7f090066
			public const int textVerifyEmail = 2131296358;
			
			// aapt resource value: 0x7f090070
			public const int textVerifyPassword = 2131296368;
			
			// aapt resource value: 0x7f090003
			public const int textView = 2131296259;
			
			// aapt resource value: 0x7f090023
			public const int textView10 = 2131296291;
			
			// aapt resource value: 0x7f09002f
			public const int textView11 = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int textView12 = 2131296304;
			
			// aapt resource value: 0x7f090022
			public const int textView13 = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int textView14 = 2131296289;
			
			// aapt resource value: 0x7f090077
			public const int textView15 = 2131296375;
			
			// aapt resource value: 0x7f090034
			public const int textView17 = 2131296308;
			
			// aapt resource value: 0x7f090078
			public const int textView2 = 2131296376;
			
			// aapt resource value: 0x7f090036
			public const int textView21 = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int textView23 = 2131296309;
			
			// aapt resource value: 0x7f090037
			public const int textView24 = 2131296311;
			
			// aapt resource value: 0x7f09003a
			public const int textView3 = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int textView4 = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int textView5 = 2131296316;
			
			// aapt resource value: 0x7f09003e
			public const int textView6 = 2131296318;
			
			// aapt resource value: 0x7f090043
			public const int textView7 = 2131296323;
			
			// aapt resource value: 0x7f090044
			public const int textView8 = 2131296324;
			
			// aapt resource value: 0x7f09007a
			public const int textView9 = 2131296378;
			
			// aapt resource value: 0x7f090025
			public const int textViewCheckResultHeader = 2131296293;
			
			// aapt resource value: 0x7f090046
			public const int textViewClaimService = 2131296326;
			
			// aapt resource value: 0x7f090026
			public const int textViewExplanation = 2131296294;
			
			// aapt resource value: 0x7f090045
			public const int textViewNewUserRegistration = 2131296325;
			
			// aapt resource value: 0x7f09004f
			public const int textZipCode = 2131296335;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int about = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int change_password = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int check_results = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int find_checks = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int forgot_password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int forgot_password_success = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Main = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int new_user = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int new_user_success = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int splash = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f07001a
			public const int button_submit = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int check_result_explanation = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int check_result_header = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int choose_your_username_and_password = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int claim_services = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int contact_information = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int find_check = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int forgot_password = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int headerdivider = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int headerlogo = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int headerlogo_change = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int headerlogo_main = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int input_claim_number = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int keep_logged_in = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int login_to_nysif = 2131165193;
			
			// aapt resource value: 0x7f070016
			public const int new_user_registration = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int new_user_sign_up_here = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int nysif_claim_number = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int nysif_claimants_can_nd_information_on_processed_bene_t_payments_for_either_workers_compensation_or_disability_bene_ts = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int password = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int screen_directions = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int settings_button = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int show_password = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int sign_in = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int username = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int where_s_my_check = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int where_s_my_check_main = 2131165198;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080004
			public const int body_h3 = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int body_title = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int button_large = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int header_title = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int new_user_registration = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int settings_button = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int user_registration_style = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
